### ISSUE TITLE
Cannot connect to host api.kimi.com:443 ssl:True

### ISSUE THREAD

**Issue by comeonzhj** [MoonshotAI/kimi-cli#53]
### What version of Kimi CLI is running?

kimi, version 0.38

### Which open platform/subscription were you using?

 Kimi For Coding

### Which model were you using?

none

### What platform is your computer?

Darwin 25.0.0 arm64 arm

### What issue are you seeing?

Failed to get models: Cannot connect to host api.kimi.com:443 ssl:True 
[SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify 
failed: self-signed certificate in certificate chain (_ssl.c:1032)')]

<img width="687" height="367" alt="Image" src="https://github.com/user-attachments/assets/479bdc40-840d-488e-bc20-2eb4a8d81f25" />

### What steps can reproduce the bug?

Use `/setup`, select `Kimi For Coding`, and enter the API KEY

**Comment by rockyyu66** [comment]
Kimi version 0.39 also has the same error

**Comment by QingChang1204** [comment]
一样的问题 没办法用

**Comment by QingChang1204** [comment]
我通过 export SSL_CERT_FILE=$(brew --prefix)/etc/ca-certificates/cert.pem 指定我的homebrw安装的证书让他能用了 不能用的可以试一下

**Comment by stdrc** [comment]
Should be fixed in 0.40. Please have a try🙏

**Comment by stdrc** [comment]
Feel free to reopen if the error still appears.

**Comment by ZenWayne** [comment]
this problem still exist

info:
kimi, version 0.51
Kimi For Coding
Darwin Kernel Version 24.5.0 arm64

output:
Failed to get models: Cannot connect to host api.kimi.com:443 ssl:default

**Comment by notedit** [comment]
问题依旧存在，应该是 kimi cli 不支持 http proxy 

---
The problem still exists, it should be that kimi cli does not support http proxy

**Comment by shiw-yang** [comment]
<img width="1920" height="2110" alt="Image" src="https://github.com/user-attachments/assets/d1088b03-d55d-4959-b365-af0214f38cb1" />

同样的问题

**Comment by ShikI-HT** [comment]
The problem still exists.

**Comment by DatalovePython** [comment]
针对 **Kimi CLI (v1.35.0)** 在 macOS 上配合代理使用时出现的 `WRONG_VERSION_NUMBER` 错误，以下是整理后的修订方案。

通过这种方式，`aiohttp` 将不再强制使用硬编码的 SSL 上下文，而是自动读取系统代理设置并正确处理握手。

---

### 解决方案：修改 `aiohttp.py` 配置

#### 1. 定位配置文件
打开终端，编辑以下路径的文件（建议先备份）：
`~/.local/share/uv/tools/kimi-cli/lib/python3.13/site-packages/kimi_cli/utils/aiohttp.py`

#### 2. 修改代码逻辑
找到 `new_client_session` 函数，将其修订为以下内容。主要改动是：**移除 `connector` 中的硬编码 SSL 设置，并启用 `trust_env=True`**。

```python
def new_client_session(
    *,
    timeout: aiohttp.ClientTimeout | None = None,
) -> aiohttp.ClientSession:
    """
    修订版：兼容系统代理与 SSL 握手
    1. 允许 ClientSession 自动读取系统环境变量 (HTTP_PROXY/HTTPS_PROXY)
    2. 移除 TCPConnector 里的硬编码 _ssl_context，避免代理协议冲突
    """
    return aiohttp.ClientSession(
        timeout=timeout or _DEFAULT_TIMEOUT,
        trust_env=True  # 关键：允许 aiohttp 识别并使用系统代理
    )
```

#### 3. 生效修订
* **保存文件**。
* **重启 Kimi CLI**：在终端重新运行 `kimi` 相关命令。

---

### 💡 为什么这样有效？
* **解决协议冲突：** `WRONG_VERSION_NUMBER` 通常是因为程序尝试用加密协议去连接代理服务器的明文端口。去掉 `TCPConnector(ssl=_ssl_context)` 后，`aiohttp` 会根据目标 URL 自动判断何时发起 SSL 握手。
* **代理兼容性：** `trust_env=True` 让程序能够识别 macOS 系统设置或终端 `export` 的代理环境变量，从而走正确的转发逻辑。

**注意：** 如果你在修改后遇到证书验证失败（Certificate Verify Failed），请确保你的代理证书已安装在 macOS 的**钥匙串访问**中并设置为“始终信任”。


---
The following is the revised solution for the `WRONG_VERSION_NUMBER` error that occurs when **Kimi CLI (v1.35.0)** is used with a proxy on macOS.

This way, `aiohttp` will no longer force the use of a hardcoded SSL context, but will instead automatically read the system proxy settings and handle the handshake correctly.

---

### Solution: Modify `aiohttp.py` configuration

#### 1. Positioning configuration file
Open the terminal and edit the file in the following path (it is recommended to back it up first):
`~/.local/share/uv/tools/kimi-cli/lib/python3.13/site-packages/kimi_cli/utils/aiohttp.py`

#### 2. Modify code logic
Find the `new_client_session` function and revise it to the following. The main changes are: **Remove hardcoded SSL settings in `connector` and enable `trust_env=True`**.

```python
def new_client_session(
    *,
    timeout: aiohttp.ClientTimeout | None = None,
) -> aiohttp.ClientSession:
    """
    Revision: Compatible system proxy and SSL handshake
    1. Allow ClientSession to automatically read system environment variables (HTTP_PROXY/HTTPS_PROXY)
    2. Remove the hard-coded _ssl_context in TCPConnector to avoid proxy protocol conflicts
    """
    return aiohttp.ClientSession(
        timeout=timeout or _DEFAULT_TIMEOUT,
        trust_env=True # Key: Allow aiohttp to recognize and use system proxies
    )
```

#### 3. Effective revision
* **Save file**.
* **Restart Kimi CLI**: Rerun `kimi` related commands in the terminal.

---

### 💡 Why does this work?
* **Resolving protocol conflicts:** `WRONG_VERSION_NUMBER` is usually caused by a program trying to use an encrypted protocol to connect to the plaintext port of the proxy server. After removing `TCPConnector(ssl=_ssl_context)`, `aiohttp` will automatically determine when to initiate an SSL handshake based on the target URL.
* **Proxy compatibility:** `trust_env=True` allows the program to identify the proxy environment variables of macOS system settings or terminal `export`, so as to implement the correct forwarding logic.

**Note:** If you encounter Certificate Verify Failed after modification, please ensure that your proxy certificate is installed in **Keychain Access** on macOS and set to "Always Trust".
